# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "oracle65"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  # config.vm.box_url = "http://domain.com/path/to/above.box"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: "192.168.56.11"

  config.vm.hostname = "box1"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider :virtualbox do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "6000"]
    vb.customize ["modifyvm", :id, "--cpus", "4"]
  end
  #
  # View the documentation for the provider you're using for more
  # information on available options.

    config.vm.provision :shell, :inline => "cd /etc/yum.repos.d ; > public-yum-ol6.repo ; wget http://mini.home.kikitux.net/stage/mini-yum-ol6.repo"
    config.vm.provision :shell, :inline => "yum install -y oracle-rdbms-server-12cR1-preinstall"
    config.vm.provision :shell, :path   => "sdc_data_asm.sh"
    config.vm.provision :shell, :path   => "sdd_fra_asm.sh"
end

